name: Publish Docker
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout twilio-php
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # The expression strips off the shortest match from the front of the string to yield just the tag name as the output
      - name: Get tagged version
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

#      - name: Setup PHP Action
#        uses: shivammathur/setup-php@2.15.0
#        with:
#          php-version: '7.4'
#
#      - name: Install dependencies
#        run: composer install

      - name: Build & Push docker image
        run: make docker-build docker-push

